### ISSUE TITLE
Can't drive DC motor with different duty cycle output.

### ISSUE THREAD

**Issue by sjhstone** [sjhstone/8051MotorController#1]
In Proteus we can drive the motor but we can't drive it in reality.

I think it might be caused by the way we send control signal.

I should try something like:

``` cpp
delay(++PWM_ON);
```

Since ULN2003A is an inverter, the output `P3^1` should be 0 when we want the controller to be running.

**Comment by nerdroychan** [comment]
I see. Will try to fix this problem.

**Comment by sjhstone** [comment]
The new `dc.c` and `step.c` are in their final versions, and works well in Proteus, they may need trivial parameter optimization to work in reality.
